env:
  global:
  - secure: H6R85WZMID91bPqrv5ajK3c2t/RwIk0Ru2cgS3k4Vt4DLXfB8+s4nh4s1FOnJH7UQDdP+GkwyByRrhE2MCMjzkkxYLQSkwP0m9QuPwvSFIpSBY9pk6WSPmOvkP6UGKJIxcA4T2X2zQKrB1pB7iyFYQnfNivvFoEz99vbxlOEpdU=
  - secure: RSJscXM4ifk5lJ1HFwyhlfuMQOwEaakXkiNYfjuke7km1ZREU79/Sxx9cCHJwbTc5Gpg8WVHlr02eJKz0spRddPqpG561rBAo3GgmJdP7W16klE4L4+bbLuAUkrL+UfWFqaO354CFfSs6XK81wpx5oxSQkgNZ8oKoUdCfBVV9n4=
  - TO=production
  - REVISION=$(git rev-parse HEAD)
  - REPO=ghettoblaster
  - USER=tubbo
language: ruby
bundler_args: --without=development
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script: bundle exec rake db:create db:migrate db:seed db:test:prepare
script: bundle exec rspec --format=documentation
after_success:
- gem install heroku
- git remote add heroku git@heroku.com:wunderkind.git
- echo 'Host heroku.com' >> ~/.ssh/config
- echo '   StrictHostKeyChecking no' >> ~/.ssh/config
- echo '   CheckHostIP no' >> ~/.ssh/config
- echo '   UserKnownHostsFile=/dev/null' >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- yes | git push heroku master
- bundle exec rake airbrake:deploy
