env:
  global:
    - secure: "YFAz6JkWHLGt1Xd9TrSzkMLCxKljn2MN/gFVFh+EIF8PHNuFtSiufcJQWDWp\nyZKpqaDnwvLNTA7v0suzmxdn/n7625nakda28l2YnIjTh2bjyhHtW8ftfUYa\nqi2M9UFvguOXbF3XTf79SZPnBDt8kXrULimPeg6jI5arBJ8fYuk="
language: ruby
bundler_args: "--without=development"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "createuser -s ghettoblaster && rake db:setup"
script: "bundle exec rspec --format=documentation"
after_success:
  # Install the Heroku gem (or the Heroku toolbelt)
  - "gem install heroku"
  # Add your Heroku git repo:
  - "git remote add heroku git@heroku.com:wunderkind.git"
  # Turn off warnings about SSH keys:
  - "echo 'Host heroku.com' >> ~/.ssh/config"
  - "echo '   StrictHostKeyChecking no' >> ~/.ssh/config"
  - "echo '   CheckHostIP no' >> ~/.ssh/config"
  - "echo '   UserKnownHostsFile=/dev/null' >> ~/.ssh/config"
  # Clear your current Heroku SSH keys:
  - "heroku keys:clear"
  # Add a new SSH key to Heroku
  - "yes | heroku keys:add"
  # Push to Heroku!
  - "yes | git push heroku master"
