env:
  global:
    - secure: H6R85WZMID91bPqrv5ajK3c2t/RwIk0Ru2cgS3k4Vt4DLXfB8+s4nh4s1FOnJH7UQDdP+GkwyByRrhE2MCMjzkkxYLQSkwP0m9QuPwvSFIpSBY9pk6WSPmOvkP6UGKJIxcA4T2X2zQKrB1pB7iyFYQnfNivvFoEz99vbxlOEpdU=
    - secure: RSJscXM4ifk5lJ1HFwyhlfuMQOwEaakXkiNYfjuke7km1ZREU79/Sxx9cCHJwbTc5Gpg8WVHlr02eJKz0spRddPqpG561rBAo3GgmJdP7W16klE4L4+bbLuAUkrL+UfWFqaO354CFfSs6XK81wpx5oxSQkgNZ8oKoUdCfBVV9n4=
    - TO=production
    - REVISION=$(git rev-parse HEAD)
    - REPO=ghettoblaster
    - USER=tubbo
    - CI=true
language: ruby
bundler_args: --without=development
before_script: bundle exec rake db
script: bundle exec rspec --format=documentation
after_success: bundle exec rake deploy RAILS_ENV=production
