party_name: "Come Correct"
flyer_url: "https://s3.amazonaws.com/flavorus/event/151948/og/74234964dbbd4ca59e8a2e755421278c.image!jpeg.401114.jpg.ComeCorrect_FR.jpg"
facebook_event: "https://www.facebook.com/events/377400385685894/"
google_analytics: "UA-32186780-2"
status: 'open'
