party_name: "Come Correct"
headline: "$10 Guest List"
flyer_url: "http://placehold.it/500x600&text=Flyer"
facebook_event: "https://www.google.com"
google_analytics: "UA-???????-?"
status: 'open'
subscribe_button: "Add me to the guest list!"
